package com.PVZ.model.entity.plants.behavior.impl;

import java.util.HashMap;
import java.util.Map;

public final class ProjectileVisuals {
    private static final Map<String, String> PATHS = new HashMap<>();

    static {
        PATHS.put("PEA", "768/INITIAL/EFFECTS/T_PEA_PROJECTILE/T_PEA_PROJECTILE.PAM");
        PATHS.put("CACTUS", "768/INITIAL/EFFECTS/T_CACTUS_PROJECTILE/T_CACTUS_PROJECTILE.PAM");
        PATHS.put("FUME", "768/INITIAL/EFFECTS/FUMESHROOM_BUBBLES/FUMESHROOM_BUBBLES.PAM");
        PATHS.put("SNOW_PEA", "768/INITIAL/EFFECTS/T_SNOW_PEA/T_SNOW_PEA.PAM");
        PATHS.put("FIRE_PEA", "768/INITIAL/EFFECTS/T_FIRE_PEA/T_FIRE_PEA.PAM");
        PATHS.put("GOO_PEA", "768/INITIAL/EFFECTS/GOOPEASHOOTER_PROJECTILES/GOOPEASHOOTER_PROJECTILES.PAM");
        PATHS.put("MEGA_GATLING", "768/INITIAL/EFFECTS/MEGAGATLING_PROJECTILE/MEGAGATLING_PROJECTILE.PAM");
        PATHS.put("PUFF", "768/INITIAL/EFFECTS/T_PUFFSHROOM_PROJECTILE/T_PUFFSHROOM_PROJECTILE.PAM");
        PATHS.put("SEA_SHROOM", "768/FULL/EFFECTS/SEASHROOM_PROJECTILE/SEASHROOM_PROJECTILE.PAM");
        PATHS.put("CABBAGE", "768/INITIAL/EFFECTS/T_CABBAGEPULT_PROJECTILE/T_CABBAGEPULT_PROJECTILE.PAM");
        PATHS.put("KERNEL", "768/INITIAL/EFFECTS/T_KERNALPULT_PROJECTILE/T_KERNALPULT_PROJECTILE.PAM");
        PATHS.put("KERNEL_BUTTER", "768/INITIAL/EFFECTS/SPLAT_KERNALPULT_BUTTER/SPLAT_KERNALPULT_BUTTER.PAM");
        PATHS.put("MELON", "768/INITIAL/EFFECTS/T_MELON_PROJECTILE/T_MELON_PROJECTILE.PAM");
        PATHS.put("WINTER_MELON", "768/FULL/EFFECTS/T_WINTERMELON_PROJECTILE/T_WINTERMELON_PROJECTILE.PAM");
        PATHS.put("PEPPER", "768/FULL/EFFECTS/PEPPERPULT_PROJECTILE/PEPPERPULT_PROJECTILE.PAM");
        PATHS.put("CITRON", "768/FULL/EFFECTS/T_CITRON_CITRUS_ORB/T_CITRON_CITRUS_ORB.PAM");
        PATHS.put("CITRON_PF", "768/FULL/EFFECTS/CITRON_PLANTFOOD_ORB/CITRON_PLANTFOOD_ORB.PAM");
        PATHS.put("CAULIPOWER", "768/INITIAL/EFFECTS/CAULIPOWER_PROJECTILE/CAULIPOWER_PROJECTILE.PAM");
        PATHS.put("ELECTRIC_BLUEBERRY", "768/INITIAL/EFFECTS/ELECTRICBLUEBERRY_CLOUD_PROJECTILE/ELECTRICBLUEBERRY_CLOUD_PROJECTILE.PAM");
        PATHS.put("BOWLING_BULB_1", "768/FULL/EFFECTS/BOWLINGBULB_PROJECTILE1/BOWLINGBULB_PROJECTILE1.PAM");
        PATHS.put("BOWLING_BULB_2", "768/FULL/EFFECTS/BOWLINGBULB_PROJECTILE2/BOWLINGBULB_PROJECTILE2.PAM");
        PATHS.put("BOWLING_BULB_3", "768/FULL/EFFECTS/BOWLINGBULB_PROJECTILE3/BOWLINGBULB_PROJECTILE3.PAM");
        PATHS.put("STARFRUIT", "768/INITIAL/EFFECTS/T_STARFRUIT_PROJECTILE/T_STARFRUIT_PROJECTILE.PAM");
        PATHS.put("STARFRUIT_PF", "768/INITIAL/EFFECTS/STARFRUIT_PROJECTILE_PLANTFOOD/STARFRUIT_PROJECTILE_PLANTFOOD.PAM");
        PATHS.put("ROTOBAGA_1", "768/FULL/EFFECTS/T_ROTORUTABAGA_PROJECTILE1/T_ROTORUTABAGA_PROJECTILE1.PAM");
        PATHS.put("ROTOBAGA_2", "768/FULL/EFFECTS/ROTORUTABAGA_PROJECTILE2/ROTORUTABAGA_PROJECTILE2.PAM");
        PATHS.put("GRAPESHOT", "768/INITIAL/EFFECTS/GRAPESHOT_PROJECTILE/GRAPESHOT_PROJECTILE.PAM");
        PATHS.put("EXPLODEONUT", "768/INITIAL/EFFECTS/EXPLODEONUT_BLINK/EXPLODEONUT_BLINK.PAM");
        PATHS.put("CHERRYBOMB", "768/FULL/EFFECTS/CHERRYBOMB_EXPLOSION_TOP/CHERRYBOMB_EXPLOSION_TOP.PAM");
        PATHS.put("JALAPENO_FIRE", "768/INITIAL/EFFECTS/JALAPENO_FIRE/JALAPENO_FIRE.PAM");
        PATHS.put("DOOMSHROOM", "768/FULL/PLANT/DOOMSHROOM/DOOMSHROOM.PAM");
        PATHS.put("TANGLE_KELP", "768/FULL/PLANT/TANGLEKELP/TANGLEKELP.PAM");
        PATHS.put("ICESHROOM", "768/FULL/EFFECTS/ICESHROOM_FX/ICESHROOM_FX.PAM");
        PATHS.put("PHAT_BEET", "768/FULL/EFFECTS/PHATBEETS_ATTACK_PULSE/PHATBEETS_ATTACK_PULSE.PAM");
        PATHS.put("KIWI_BEAST", "768/INITIAL/EFFECTS/KIWIBEAST_ATTACK_PULSE/KIWIBEAST_ATTACK_PULSE.PAM");
        PATHS.put("TORCHWOOD_HIT", "768/INITIAL/EFFECTS/TORCHWOOD_HIT_EFFECTS/TORCHWOOD_HIT_EFFECTS.PAM");
        PATHS.put("CATTAIL_HOMING", "768/INITIAL/EFFECTS/HOMING_THISTLE_PROJECTILE/HOMING_THISTLE_PROJECTILE.PAM");
        PATHS.put("POTATO_MINE_EXPLOSION", "768/INITIAL/EFFECTS/GRAVEBUSTER_EXPLOSION_POTATOMINE/GRAVEBUSTER_EXPLOSION_POTATOMINE.PAM");
        PATHS.put("PRIMAL_POTATO_MINE_EXPLOSION", "768/INITIAL/EFFECTS/GRAVEBUSTER_EXPLOSION_POTATOMINE/GRAVEBUSTER_EXPLOSION_POTATOMINE.PAM");
        PATHS.put("SQUASH", "768/INITIAL/PLANT/SQUASH/SQUASH.PAM");
        PATHS.put("HOTPOTATO_STEAM", "768/FULL/EFFECTS/HOTPOTATO_STEAMFX/HOTPOTATO_STEAMFX.PAM");
        PATHS.put("GRAVEBUSTER_DIRT", "768/INITIAL/EFFECTS/GRAVEBUSTER_DIRT/GRAVEBUSTER_DIRT.PAM");
        PATHS.put("GRAPESHOT", "768/INITIAL/EFFECTS/GRAPESHOT_PROJECTILE/GRAPESHOT_PROJECTILE.PAM");
        PATHS.put("EXPLODEONUT", "768/INITIAL/EFFECTS/EXPLODEONUT_BLINK/EXPLODEONUT_BLINK.PAM");

        PATHS.put("ICE_SHROOM", "768/FULL/EFFECTS/ICESHROOM_PROJECTILE/ICESHROOM_PROJECTILE.PAM");
        PATHS.put("GARLIC", "768/INITIAL/EFFECTS/GARLIC_PROJECTILE/GARLIC_PROJECTILE.PAM");
    }

    private ProjectileVisuals() {
    }

    public static String getPath(String visualKey) {
        return visualKey == null ? null : PATHS.get(visualKey);
    }
}
