package com.PVZ.model.entity.plants.behavior.impl;

import java.util.HashMap;
import java.util.Map;

public final class ProjectileVisuals {
    private static final Map<String, String> PATHS = new HashMap<>();

    static {
        PATHS.put("PEA", "768/INITIAL/EFFECTS/T_PEA_PROJECTILE/T_PEA_PROJECTILE.PAM");
        PATHS.put("CACTUS", "768/INITIAL/EFFECTS/T_CACTUS_PROJECTILE/T_CACTUS_PROJECTILE.PAM");
        PATHS.put("FUME", "768/INITIAL/EFFECTS/FUMESHROOM_BUBBLES/FUMESHROOM_BUBBLES.PAM");
        PATHS.put("SNOW_PEA", "768/INITIAL/EFFECTS/T_SNOW_PEA/T_SNOW_PEA.PAM");
        PATHS.put("FIRE_PEA", "768/INITIAL/EFFECTS/T_FIRE_PEA/T_FIRE_PEA.PAM");
        PATHS.put("GOO_PEA", "768/INITIAL/EFFECTS/GOOPEASHOOTER_PROJECTILES/GOOPEASHOOTER_PROJECTILES.PAM");
        PATHS.put("MEGA_GATLING", "768/INITIAL/EFFECTS/MEGAGATLING_PROJECTILE/MEGAGATLING_PROJECTILE.PAM");
        PATHS.put("PUFF", "768/INITIAL/EFFECTS/T_PUFFSHROOM_PROJECTILE/T_PUFFSHROOM_PROJECTILE.PAM");
        PATHS.put("SEA_SHROOM", "768/FULL/EFFECTS/SEASHROOM_PROJECTILE/SEASHROOM_PROJECTILE.PAM");
        PATHS.put("CABBAGE", "768/INITIAL/EFFECTS/T_CABBAGEPULT_PROJECTILE/T_CABBAGEPULT_PROJECTILE.PAM");
        PATHS.put("KERNEL", "768/INITIAL/EFFECTS/T_KERNALPULT_PROJECTILE/T_KERNALPULT_PROJECTILE.PAM");
        PATHS.put("KERNEL_BUTTER", "768/INITIAL/EFFECTS/SPLAT_KERNALPULT_BUTTER/SPLAT_KERNALPULT_BUTTER.PAM");
        PATHS.put("MELON", "768/INITIAL/EFFECTS/T_MELON_PROJECTILE/T_MELON_PROJECTILE.PAM");
        PATHS.put("WINTER_MELON", "768/FULL/EFFECTS/T_WINTERMELON_PROJECTILE/T_WINTERMELON_PROJECTILE.PAM");
        PATHS.put("PEPPER", "768/FULL/EFFECTS/PEPPERPULT_PROJECTILE/PEPPERPULT_PROJECTILE.PAM");
        PATHS.put("CITRON", "768/FULL/EFFECTS/T_CITRON_CITRUS_ORB/T_CITRON_CITRUS_ORB.PAM");
        PATHS.put("CITRON_PF", "768/FULL/EFFECTS/CITRON_PLANTFOOD_ORB/CITRON_PLANTFOOD_ORB.PAM");
        PATHS.put("CAULIPOWER", "768/INITIAL/EFFECTS/CAULIPOWER_PROJECTILE/CAULIPOWER_PROJECTILE.PAM");
        PATHS.put("ELECTRIC_BLUEBERRY", "768/INITIAL/EFFECTS/"+
            "ELECTRICBLUEBERRY_CLOUD_PROJECTILE/ELECTRICBLUEBERRY_CLOUD_PROJECTILE.PAM");
        PATHS.put("BOWLING_BULB_1", "768/FULL/EFFECTS/BOWLINGBULB_PROJECTILE1/BOWLINGBULB_PROJECTILE1.PAM");
        PATHS.put("BOWLING_BULB_2", "768/FULL/EFFECTS/BOWLINGBULB_PROJECTILE2/BOWLINGBULB_PROJECTILE2.PAM");
        PATHS.put("BOWLING_BULB_3", "768/FULL/EFFECTS/BOWLINGBULB_PROJECTILE3/BOWLINGBULB_PROJECTILE3.PAM");
        PATHS.put("STARFRUIT", "768/INITIAL/EFFECTS/T_STARFRUIT_PROJECTILE/T_STARFRUIT_PROJECTILE.PAM");
        PATHS.put("STARFRUIT_PF", "768/INITIAL/EFFECTS/STARFRUIT_PROJECTILE_PLANTFOOD/" +
            "STARFRUIT_PROJECTILE_PLANTFOOD.PAM");
        PATHS.put("ROTOBAGA_1", "768/FULL/EFFECTS/T_ROTORUTABAGA_PROJECTILE1/T_ROTORUTABAGA_PROJECTILE1.PAM");
        PATHS.put("ROTOBAGA_2", "768/FULL/EFFECTS/ROTORUTABAGA_PROJECTILE2/ROTORUTABAGA_PROJECTILE2.PAM");
        PATHS.put("GRAPESHOT", "768/INITIAL/EFFECTS/GRAPESHOT_PROJECTILE/GRAPESHOT_PROJECTILE.PAM");
        PATHS.put("GRAPESHOT_FORWARD", "768/INITIAL/EFFECTS/GRAPESHOT_PROJECTILE/GRAPESHOT_PROJECTILE.PAM");
        PATHS.put("GRAPESHOT_BACKWARD", "768/INITIAL/EFFECTS/GRAPESHOT_PROJECTILE/GRAPESHOT_PROJECTILE.PAM");
        PATHS.put("GRAPESHOT_UP", "768/INITIAL/EFFECTS/GRAPESHOT_PROJECTILE/GRAPESHOT_PROJECTILE.PAM");
        PATHS.put("GRAPESHOT_DOWN", "768/INITIAL/EFFECTS/GRAPESHOT_PROJECTILE/GRAPESHOT_PROJECTILE.PAM");
        PATHS.put("ICE_SHROOM", "768/FULL/EFFECTS/ICESHROOM_PROJECTILE/ICESHROOM_PROJECTILE.PAM");
        PATHS.put("GARLIC", "768/INITIAL/EFFECTS/GARLIC_PROJECTILE/GARLIC_PROJECTILE.PAM");
    }

    private static final Map<String, String> HIT_PATHS = new HashMap<>();
    private static final Map<String, String> HIT_CLIPS = new HashMap<>();
    static {
        HIT_PATHS.put("PEA", "768/INITIAL/EFFECTS/SPLAT_PEA/SPLAT_PEA.PAM");
        HIT_PATHS.put("SNOW_PEA", "768/INITIAL/EFFECTS/SPLAT_SNOW_PEA/SPLAT_SNOW_PEA.PAM");
        HIT_PATHS.put("CACTUS", "768/INITIAL/EFFECTS/CACTUS_PROJECTILE_HIT/CACTUS_PROJECTILE_HIT.PAM");
        HIT_PATHS.put("FUME", "768/INITIAL/EFFECTS/FUMESHROOM_BUBBLES_HIT/FUMESHROOM_BUBBLES_HIT.PAM");
        HIT_PATHS.put("CITRON", "768/FULL/EFFECTS/T_CITRON_CITRUS_ORB_HIT/T_CITRON_CITRUS_ORB_HIT.PAM");
        HIT_PATHS.put("GOO_PEA", "768/INITIAL/EFFECTS/GOOPEASHOOTER_PROJECTILES/GOOPEASHOOTER_PROJECTILES.PAM");
        HIT_PATHS.put("GRAPESHOT", "768/INITIAL/EFFECTS/GRAPESHOT_HIT/GRAPESHOT_HIT.PAM");
        HIT_PATHS.put("KERNEL_BUTTER", "768/INITIAL/EFFECTS/SPLAT_KERNALPULT_BUTTER/SPLAT_KERNALPULT_BUTTER.PAM");
        HIT_PATHS.put("MELON", "768/INITIAL/EFFECTS/T_SPLAT_MELONPULT/T_SPLAT_MELONPULT.PAM");
        HIT_PATHS.put("WINTER_MELON", "768/INITIAL/EFFECTS/T_SPLAT_WINTERMELON/T_SPLAT_WINTERMELON.PAM");
        HIT_PATHS.put("STARFRUIT", "768/INITIAL/EFFECTS/T_STARFRUIT_PROJECTILE_HIT/T_STARFRUIT_PROJECTILE_HIT.PAM");
        HIT_PATHS.put("ROTOBAGA_1", "768/FULL/EFFECTS/T_ROTORUTABAGA_PROJECTILE_HIT/T_ROTORUTABAGA_PROJECTILE_HIT.PAM");
        HIT_PATHS.put("GARLIC", "768/INITIAL/EFFECTS/GARLIC_STINK_LINES/GARLIC_STINK_LINES.PAM");
        HIT_CLIPS.put("STARFRUIT", "animation");
    }

    public static String getHitPathForProjectile(Projectile p) {
        if (p == null) return null;
        Object key = p.getExtra("visualKey");
        return key instanceof String ? HIT_PATHS.get(key) : null;
    }

    public static String getHitClipForProjectile(Projectile p) {
        if (p == null) return "animation";
        Object key = p.getExtra("visualKey");
        return key instanceof String ? getHitClipForVisualKey((String) key) : "animation";
    }

    public static String getHitPathForVisualKey(String visualKey) {
        return visualKey == null ? null : HIT_PATHS.get(visualKey);
    }

    public static String getHitClipForVisualKey(String visualKey) {
        return visualKey == null ? "animation" : HIT_CLIPS.getOrDefault(visualKey, "animation");
    }

    private ProjectileVisuals() {
    }

    public static String getPath(String visualKey) {
        return visualKey == null ? null : PATHS.get(visualKey);
    }
}
