package com.PVZ.view.screen.ui;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Upgrade descriptions generated from the Plants sheet in plants(1).xlsx.
 * Keyed by plant name + target level so each plant/level keeps its own text.
 */
public final class UpgradeDescriptionCatalog {
    private static final Map<String, String> DESCRIPTIONS = new HashMap<>();

    static {
        DESCRIPTIONS.put("sunflower#2", "Sun production time decreases by 2 seconds.");
        DESCRIPTIONS.put("sunflower#3", "Health increases by 150.");
        DESCRIPTIONS.put("sunflower#4", "Increases the chance of producing double Sun.");
        DESCRIPTIONS.put("twin_sunflower#2", "Sun production time decreases by 2 seconds.");
        DESCRIPTIONS.put("twin_sunflower#3", "Health increases by 150.");
        DESCRIPTIONS.put("twin_sunflower#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("sun_shroom#2", "Growth time decreases by 5 seconds.");
        DESCRIPTIONS.put("sun_shroom#3", "Health increases by 150.");
        DESCRIPTIONS.put("sun_shroom#4", "Increases the chance of producing double Sun.");
        DESCRIPTIONS.put("primal_sunflower#2", "Sun production time decreases by 2 seconds.");
        DESCRIPTIONS.put("primal_sunflower#3", "Health increases by 150.");
        DESCRIPTIONS.put("primal_sunflower#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("gold_bloom#2", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("gold_bloom#3", "Immediate Sun gain increases by 50.");
        DESCRIPTIONS.put("gold_bloom#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("peashooter#2", "Damage increases by 10.");
        DESCRIPTIONS.put("peashooter#3", "Health increases by 150.");
        DESCRIPTIONS.put("peashooter#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("repeater#2", "Damage increases by 10.");
        DESCRIPTIONS.put("repeater#3", "Health increases by 200.");
        DESCRIPTIONS.put("repeater#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("threepeater#2", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("threepeater#3", "Damage increases by 10.");
        DESCRIPTIONS.put("threepeater#4", "Health increases by 200.");
        DESCRIPTIONS.put("snow_pea#2", "Damage increases by 10.");
        DESCRIPTIONS.put("snow_pea#3", "Chill duration increases by 2 seconds.");
        DESCRIPTIONS.put("snow_pea#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("rotobaga#2", "Damage increases by 10.");
        DESCRIPTIONS.put("rotobaga#3", "Health increases by 150.");
        DESCRIPTIONS.put("rotobaga#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("pea_pod#2", "Damage increases by 10.");
        DESCRIPTIONS.put("pea_pod#3", "Health increases by 200.");
        DESCRIPTIONS.put("pea_pod#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("split_pea#2", "Damage increases by 10.");
        DESCRIPTIONS.put("split_pea#3", "Health increases by 200.");
        DESCRIPTIONS.put("split_pea#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("citron#2", "Charge time decreases by 1 second.");
        DESCRIPTIONS.put("citron#3", "Damage increases by 150.");
        DESCRIPTIONS.put("citron#4", "Planting cost decreases by 50 Sun.");
        DESCRIPTIONS.put("caulipower#2", "Recharge time decreases by 2 seconds.");
        DESCRIPTIONS.put("caulipower#3", "Health increases by 150.");
        DESCRIPTIONS.put("caulipower#4", "Planting cost decreases by 50 Sun.");
        DESCRIPTIONS.put("electric_blueberry#2", "Recharge time decreases by 2 seconds.");
        DESCRIPTIONS.put("electric_blueberry#3", "Improves the plant's target priority.");
        DESCRIPTIONS.put("electric_blueberry#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("bowling_bulb#2", "Regeneration time decreases by 1 second.");
        DESCRIPTIONS.put("bowling_bulb#3", "Damage increases by 15.");
        DESCRIPTIONS.put("bowling_bulb#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("cactus#2", "The plant can pierce 1 more target.");
        DESCRIPTIONS.put("cactus#3", "Damage increases by 10.");
        DESCRIPTIONS.put("cactus#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("fire_peashooter#2", "Damage increases by 10.");
        DESCRIPTIONS.put("fire_peashooter#3", "Health increases by 200.");
        DESCRIPTIONS.put("fire_peashooter#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("starfruit#2", "Attack speed increases by 10%.");
        DESCRIPTIONS.put("starfruit#3", "Damage increases by 10.");
        DESCRIPTIONS.put("starfruit#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("goo_peashooter#2", "Damage dealt per tick increases by 5.");
        DESCRIPTIONS.put("goo_peashooter#3", "Health increases by 150.");
        DESCRIPTIONS.put("goo_peashooter#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("mega_gatling_pea#2", "Damage increases by 10.");
        DESCRIPTIONS.put("mega_gatling_pea#3", "Increases the chance of triggering Plant Food by 5%.");
        DESCRIPTIONS.put("mega_gatling_pea#4", "Planting cost decreases by 50 Sun.");
        DESCRIPTIONS.put("sea_shroom#2", "Attack range increases by 1 tile.");
        DESCRIPTIONS.put("sea_shroom#3", "Damage increases by 5.");
        DESCRIPTIONS.put("sea_shroom#4", "Plant lifespan increases by 10 seconds.");
        DESCRIPTIONS.put("puff_shroom#2", "Plant lifespan increases by 10 seconds.");
        DESCRIPTIONS.put("puff_shroom#3", "Damage increases by 10.");
        DESCRIPTIONS.put("puff_shroom#4", "Attack range increases by 1 tile.");
        DESCRIPTIONS.put("fume_shroom#2", "Attack range increases by 1 tile.");
        DESCRIPTIONS.put("fume_shroom#3", "Damage increases by 10.");
        DESCRIPTIONS.put("fume_shroom#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("cabbage_pult#2", "Damage increases by 10.");
        DESCRIPTIONS.put("cabbage_pult#3", "Attack speed increases by 15%.");
        DESCRIPTIONS.put("cabbage_pult#4", "Health increases by 150.");
        DESCRIPTIONS.put("kernel_pult#2", "Butter activation chance increases by 5%.");
        DESCRIPTIONS.put("kernel_pult#3", "Damage increases by 10.");
        DESCRIPTIONS.put("kernel_pult#4", "Health increases by 150.");
        DESCRIPTIONS.put("melon_pult#2", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("melon_pult#3", "Area damage increases by 15.");
        DESCRIPTIONS.put("melon_pult#4", "Damage increases by 30.");
        DESCRIPTIONS.put("winter_melon#2", "Planting cost decreases by 50 Sun.");
        DESCRIPTIONS.put("winter_melon#3", "Area damage increases by 15.");
        DESCRIPTIONS.put("winter_melon#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("pepper_pult#2", "Damage increases by 15.");
        DESCRIPTIONS.put("pepper_pult#3", "Warmth radius increases by 1 tile.");
        DESCRIPTIONS.put("pepper_pult#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("potato_mine#2", "Arming time decreases by 3 seconds.");
        DESCRIPTIONS.put("potato_mine#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("potato_mine#4", "Damage increases by 600.");
        DESCRIPTIONS.put("primal_potato_mine#2", "Arming time decreases by 1 second.");
        DESCRIPTIONS.put("primal_potato_mine#3", "Recharge time decreases by 3 seconds.");
        DESCRIPTIONS.put("primal_potato_mine#4", "Damage increases by 400.");
        DESCRIPTIONS.put("cherry_bomb#2", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("cherry_bomb#3", "Damage increases by 600.");
        DESCRIPTIONS.put("cherry_bomb#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("squash#2", "Recharge time decreases by 3 seconds.");
        DESCRIPTIONS.put("squash#3", "Damage increases by 600.");
        DESCRIPTIONS.put("squash#4", "The plant can now crush up to two zombies.");
        DESCRIPTIONS.put("grapeshot#2", "Damage increases by 600.");
        DESCRIPTIONS.put("grapeshot#3", "The projectile can bounce 1 more time.");
        DESCRIPTIONS.put("grapeshot#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("jalapeno#2", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("jalapeno#3", "Damage increases by 600.");
        DESCRIPTIONS.put("jalapeno#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("doom_shroom#2", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("doom_shroom#3", "Damage increases by 800.");
        DESCRIPTIONS.put("doom_shroom#4", "Planting cost decreases by 50 Sun.");
        DESCRIPTIONS.put("tangle_kelp#2", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("tangle_kelp#3", "Target count increases by 1.");
        DESCRIPTIONS.put("tangle_kelp#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("iceberg_lettuce#2", "Recharge time decreases by 2 seconds.");
        DESCRIPTIONS.put("iceberg_lettuce#3", "Freeze duration increases by 2 seconds.");
        DESCRIPTIONS.put("iceberg_lettuce#4", "Planting cost remains unchanged.");
        DESCRIPTIONS.put("bonk_choy#2", "Damage increases by 5.");
        DESCRIPTIONS.put("bonk_choy#3", "Attack speed increases by 10%.");
        DESCRIPTIONS.put("bonk_choy#4", "Health increases by 200.");
        DESCRIPTIONS.put("phat_beet#2", "Damage increases by 10.");
        DESCRIPTIONS.put("phat_beet#3", "Attack speed increases by 10%.");
        DESCRIPTIONS.put("phat_beet#4", "Health increases by 200.");
        DESCRIPTIONS.put("chomper#2", "Digest time decreases by 2 seconds.");
        DESCRIPTIONS.put("chomper#3", "Health increases by 200.");
        DESCRIPTIONS.put("chomper#4", "Digest time decreases by 3 seconds.");
        DESCRIPTIONS.put("wasabi_whip#2", "Damage increases by 10.");
        DESCRIPTIONS.put("wasabi_whip#3", "Attack range increases by 1 tile.");
        DESCRIPTIONS.put("wasabi_whip#4", "Health increases by 200.");
        DESCRIPTIONS.put("kiwibeast#2", "Health increases by 200.");
        DESCRIPTIONS.put("kiwibeast#3", "Damage increases by 15.");
        DESCRIPTIONS.put("kiwibeast#4", "Maximum size increases by 1 stage.");
        DESCRIPTIONS.put("wall_nut#2", "Health increases by 1000.");
        DESCRIPTIONS.put("wall_nut#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("wall_nut#4", "Health increases by 1500.");
        DESCRIPTIONS.put("tall_nut#2", "Health increases by 2000.");
        DESCRIPTIONS.put("tall_nut#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("tall_nut#4", "Health increases by 3000.");
        DESCRIPTIONS.put("endurian#2", "Reflected damage increases by 5.");
        DESCRIPTIONS.put("endurian#3", "Health increases by 1000.");
        DESCRIPTIONS.put("endurian#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("garlic#2", "Health increases by 150.");
        DESCRIPTIONS.put("garlic#3", "Recharge time decreases by 3 seconds.");
        DESCRIPTIONS.put("garlic#4", "Health increases by 250.");
        DESCRIPTIONS.put("sweet_potato#2", "Health increases by 1000.");
        DESCRIPTIONS.put("sweet_potato#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("sweet_potato#4", "Health increases by 1500.");
        DESCRIPTIONS.put("explode_o_nut#2", "Health increases by 1000.");
        DESCRIPTIONS.put("explode_o_nut#3", "Explosion damage increases by 200.");
        DESCRIPTIONS.put("explode_o_nut#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("pumpkin#2", "Health increases by 1000.");
        DESCRIPTIONS.put("pumpkin#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("pumpkin#4", "Health increases by 1500.");
        DESCRIPTIONS.put("sun_bean#2", "Each hit produces 5 more Sun.");
        DESCRIPTIONS.put("sun_bean#3", "Health increases by 150.");
        DESCRIPTIONS.put("sun_bean#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("torchwood#2", "Health increases by 300.");
        DESCRIPTIONS.put("torchwood#3", "The plant now creates an area explosion when it is defeated.");
        DESCRIPTIONS.put("torchwood#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("magnet_shroom#2", "Attack range increases by 1 tile.");
        DESCRIPTIONS.put("magnet_shroom#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("magnet_shroom#4", "Health increases by 200.");
        DESCRIPTIONS.put("hypno_shroom#2", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("hypno_shroom#3", "Increases the HP of the zombie created by this plant.");
        DESCRIPTIONS.put("hypno_shroom#4", "Increases the damage of the zombie created by this plant.");
        DESCRIPTIONS.put("cat_tail#2", "Damage increases by 10.");
        DESCRIPTIONS.put("cat_tail#3", "Health increases by 200.");
        DESCRIPTIONS.put("cat_tail#4", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("imitater#2", "Recharge time decreases by 2 seconds.");
        DESCRIPTIONS.put("imitater#3", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("imitater#4", "The Plant Food effect now activates when the plant enters the lawn.");
        DESCRIPTIONS.put("ice_shroom#2", "Freeze duration increases by 2 seconds.");
        DESCRIPTIONS.put("ice_shroom#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("ice_shroom#4", "Damage increases by 50.");
        DESCRIPTIONS.put("lily_pad#2", "Planting cost decreases by 25 Sun.");
        DESCRIPTIONS.put("lily_pad#3", "Health increases by 200.");
        DESCRIPTIONS.put("lily_pad#4", "Recharge time decreases by 2 seconds.");
        DESCRIPTIONS.put("hot_potato#2", "Recharge time decreases by 2 seconds.");
        DESCRIPTIONS.put("hot_potato#3", "Melts ice in a 3×3 area.");
        DESCRIPTIONS.put("hot_potato#4", "The plant now explodes when its action finishes.");
        DESCRIPTIONS.put("grave_buster#2", "Grave-eating time decreases by 1 second.");
        DESCRIPTIONS.put("grave_buster#3", "Recharge time decreases by 2 seconds.");
        DESCRIPTIONS.put("grave_buster#4", "The plant now explodes when its action finishes.");
        DESCRIPTIONS.put("enlighten_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("enlighten_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("enlighten_mint#4", "Resets the cooldowns of plants in the same family.");
        DESCRIPTIONS.put("appease_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("appease_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("appease_mint#4", "Resets the cooldowns of plants in the same family.");
        DESCRIPTIONS.put("arma_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("arma_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("arma_mint#4", "Resets the cooldowns of plants in the same family.");
        DESCRIPTIONS.put("bombard_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("bombard_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("bombard_mint#4", "Resets the cooldowns of plants in the same family.");
        DESCRIPTIONS.put("enforce_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("enforce_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("enforce_mint#4", "Resets the cooldowns of plants in the same family.");
        DESCRIPTIONS.put("reinforce_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("reinforce_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("reinforce_mint#4", "Resets the cooldowns of plants in the same family.");
        DESCRIPTIONS.put("enchant_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("enchant_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("enchant_mint#4", "Resets the cooldowns of plants in the same family.");
        DESCRIPTIONS.put("pierce_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("pierce_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("pierce_mint#4", "Resets the cooldowns of plants in the same family.");
        DESCRIPTIONS.put("cattail_mint#2", "Plant Food effect duration increases by 1 seconds.");
        DESCRIPTIONS.put("cattail_mint#3", "Recharge time decreases by 5 seconds.");
        DESCRIPTIONS.put("cattail_mint#4", "Resets the cooldowns of plants in the same family.");
    }

    private UpgradeDescriptionCatalog() {}

    public static String find(String plantName, int level) {
        if (plantName == null) return null;
        return DESCRIPTIONS.get(normalize(plantName) + "#" + level);
    }

    private static String normalize(String value) {
        return value.toLowerCase(Locale.ROOT)
            .replaceAll("[^a-z0-9]+", "_")
            .replaceAll("^_+|_+$", "");
    }
}